import { PageHeader } from "@/components/layout/PageHeader";
import { Sparkles, AlertTriangle, TrendingUp, ShieldAlert } from "lucide-react";

const factors = [
  { label: "Declared value variance", score: 92, weight: "High" },
  { label: "Exporter risk history", score: 38, weight: "Medium" },
  { label: "HS code accuracy", score: 12, weight: "Low" },
  { label: "Document completeness", score: 22, weight: "Low" },
  { label: "Route anomaly detection", score: 64, weight: "Medium" },
];

export default function Risk() {
  const overall = 78;

  return (
    <>
      <PageHeader
        eyebrow="AI Risk Engine"
        title="Risk Analysis"
        description="Real-time risk scoring with explainable AI decisioning for shipment ZSB-2401-8818."
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        {/* Gauge */}
        <div className="bg-card rounded-2xl p-6 border border-border/60 shadow-card flex flex-col items-center text-center">
          <div className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-4">Overall Risk Score</div>
          <div className="relative w-48 h-48">
            <svg viewBox="0 0 200 200" className="w-full h-full -rotate-90">
              <circle cx="100" cy="100" r="80" stroke="hsl(var(--muted))" strokeWidth="14" fill="none" />
              <circle
                cx="100" cy="100" r="80"
                stroke="hsl(var(--destructive))"
                strokeWidth="14"
                fill="none"
                strokeLinecap="round"
                strokeDasharray={`${(overall / 100) * 502} 502`}
              />
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <div className="text-5xl font-bold text-destructive">{overall}</div>
              <div className="text-xs uppercase tracking-wider text-muted-foreground">/ 100</div>
            </div>
          </div>
          <div className="inline-flex items-center gap-2 mt-4 px-3 py-1.5 bg-destructive-soft text-destructive rounded-full text-sm font-semibold">
            <ShieldAlert className="h-4 w-4" /> High Risk — Manual Review
          </div>
        </div>

        {/* AI Explanation */}
        <div className="lg:col-span-2 bg-gradient-primary text-white rounded-2xl p-6 shadow-elegant">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-10 w-10 rounded-xl bg-white/15 backdrop-blur flex items-center justify-center">
              <Sparkles className="h-5 w-5" />
            </div>
            <div>
              <div className="font-semibold">AI Explanation</div>
              <div className="text-xs text-white/70">Generated by Customs AI v4.2</div>
            </div>
          </div>
          <div className="bg-white/10 backdrop-blur rounded-xl p-5 space-y-3 text-sm leading-relaxed">
            <p>
              <strong className="text-warning">⚠ Critical:</strong> The declared value of <strong>$24,500</strong> is
              <strong> 27% lower</strong> than the median market price for similar pharmaceutical shipments from this
              origin (HS 3004.90). This is the strongest risk signal.
            </p>
            <p>
              <strong>Secondary signals:</strong> Exporter "Acme Trading" has 2 historical undervaluation cases in the
              last 18 months. Route via Dubai → Baku has a 14% higher historical fraud rate than direct routes.
            </p>
            <p className="text-white/80">
              <strong>Recommended action:</strong> Hold for physical inspection. Request original commercial
              invoice and bank transfer evidence.
            </p>
          </div>
        </div>
      </div>

      <div className="bg-card rounded-2xl p-6 border border-border/60 shadow-card">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="text-base font-semibold">Risk Factor Breakdown</h3>
            <p className="text-sm text-muted-foreground mt-0.5">Individual model contributions</p>
          </div>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <TrendingUp className="h-4 w-4" /> Updated 4s ago
          </div>
        </div>

        <div className="space-y-5">
          {factors.map((f) => (
            <div key={f.label}>
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-foreground">{f.label}</span>
                  <span className="text-[10px] uppercase tracking-wider px-1.5 py-0.5 rounded bg-muted text-muted-foreground font-semibold">
                    {f.weight}
                  </span>
                </div>
                <span className={`text-sm font-bold ${
                  f.score > 70 ? "text-destructive" : f.score > 30 ? "text-warning-foreground" : "text-success"
                }`}>{f.score}</span>
              </div>
              <div className="h-2 rounded-full bg-muted overflow-hidden">
                <div
                  className="h-full rounded-full transition-all"
                  style={{
                    width: `${f.score}%`,
                    background: f.score > 70 ? "hsl(var(--destructive))" : f.score > 30 ? "hsl(var(--warning))" : "hsl(var(--success))",
                  }}
                />
              </div>
            </div>
          ))}
        </div>

        <div className="mt-6 p-4 rounded-xl bg-warning-soft border border-warning/30 flex gap-3">
          <AlertTriangle className="h-5 w-5 text-warning-foreground shrink-0 mt-0.5" />
          <div className="text-sm">
            <strong>Officer note:</strong> Combine value-variance and exporter-history signals to justify hold-decision per Customs Code Article 47.
          </div>
        </div>
      </div>
    </>
  );
}
